source 'https://rubygems.org'
gem "rake"
gem "tilt"
gem "temple"
gem "slim"
gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-flash"
gem "bcrypt-ruby"
gem "mysql2"
gem "sequel"
gem "sass"
gem "json"
gem "encrypted_cookie"
gem "rack-contrib"
gem "rack_csrf"
gem "htmlentities"
gem "r18n-core"
gem "sinatra-r18n"
gem "thin"
gem "rubytree"

group :development, :test do
  gem "rspec"
  gem "webrat"
  gem "capybara"
  gem "launchy"
  gem "cucumber"
  gem "cucumber-sinatra"
  # gem "shotgun"
  gem "poltergeist"
  # gem 'selenium-webdriver'
  # gem "mocha"
  gem 'test-unit','= 2.5.5' 
  gem "test-unit-full"
  # gem "rdoc"
end
