source 'https://rubygems.org'
gem "tilt"
gem "temple"
gem "slim"
gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-flash"
gem "bcrypt-ruby"
gem "mysql2"
gem "sequel"
gem "sass"
gem "better_errors"
gem "kss"
gem "encrypted_cookie"
gem "rack_csrf"
gem "sinatra-r18n"
gem "htmlentities"
gem "r18n-core"
gem "thin"

group :development, :test do
  gem "rspec"
  gem "webrat"
  gem "capybara"
  gem "launchy"
  gem "cucumber"
  gem "cucumber-sinatra"
  gem "shotgun"
  gem "poltergeist"
  gem "mocha"
  gem "test-unit-full"
end
