source 'https://rubygems.org'
gem "rake"
gem "tilt"
gem "temple"
gem "slim"
gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-flash"
gem "bcrypt-ruby"
gem "mysql2"
gem "sequel"
gem "sass"
gem "json"
gem "encrypted_cookie"
gem "rack-contrib"
gem "rack_csrf"
gem "htmlentities"
gem "r18n-core"
gem "i18n"
gem "sinatra-r18n"
gem "thin"
gem "rubytree"

group :development, :test do
  gem "awesome_print"
  gem "rspec"
  gem "webrat"
  gem "capybara"
  gem "cucumber"
  gem "cucumber-sinatra"
  gem "poltergeist"
  gem 'test-unit','= 2.5.5' 
end
